name: HapsyPlugin
author: LeRoiDesKiwis
version: 1.5
main: fr.leroideskiwis.hapsyplugin.Main
commands:
  msg:
    description: envoie un message
    aliases: m
  r:
    description: repondre a un message