name: UtilsPlugin
author: LeRoiDesKiwis
version: 1.0
main: fr.leroideskiwis.utilsplugin.Main
commands:
  god:
    description: permet d'annuler tout les degats recu
  invsee:
  invender:
  butcher:
  test:
  broadcast:
    aliases: [bc]
  getKeyN:
  clearend:
  getKeyE:
  changeWorld:
  enchant: