name: enderpearlGame
author: LeRoiDesKiwis
version: 0.5
main: fr.leroideskiwis.enderpearlbattle.Main
commands:
  enderpearlgame:
    description: rejoindre une partie de enderpearlbattle
  leaveepg:
    description: quitter la partie
  elimine:
  toggleDisable: